name: Run Robot Tests Cases

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          sudo apt-get update
          sudo apt-get install -y xvfb
      - name: Run Robot Framework Tests
        run: |
          xvfb-run robot --outputdir Results Tests/
        working-directory: ./
      - name: Upload Test Results
        uses: actions/upload-artifact@v2
        with:
          name: Test Results
          path: Results/
