name: Run Robot Framework Tests in a Docker

on:
  workflow_dispatch:

env:
  IMAGE_NAME: luckylaksh8/sfrobottest
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Pull Docker image
      run: |
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        docker pull $DOCKER_USERNAME/$IMAGE_NAME:latest

    - name: Run tests
      run: |
        docker run -v ${PWD}/Tests:app/Tests -v ${PWD}/Results:app/Results -v ${PWD}/Resources:app/Resources $DOCKER_USERNAME/$IMAGE_NAME:latest
