name: Run Robot Framework Tests in a Docker

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run Robot Framework Tests In Docker
      run: |
        docker run --rm \
          -v ${{ github.workspace }}/Tests:/Tests \
          -v ${{ github.workspace }}/Results:/Results \
          -v ${{ github.workspace }}/Resources:/Resources \
          luckylaksh8/sfrobottest:latest \
          /Tests

